name: Node.js Package (GitHub Packages)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0              
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ShlomoNus'
      - run: npm ci
      - run: npm run build            
      - run: npx semantic-release    
